name: build-and-release

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install conan
         run: pip3 install conan
      
      - name: Configure CMake
         run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=DEBUG

      - name: Build
         run: cmake --build ${{github.workspace}}/build --config DEBUG

      - name: cd to build dir
         run: cd ${{github.workspace}}/build

      - name: Run tests
         run: ctest
